### ISSUE TITLE
Better Styles for Website

### ISSUE THREAD

**Issue by tomopagu** [tomopagu/disbott#17]
Our Website (https://disbott.pagu.co/) is a little bit bland and the white background can be very bright so I'd like it if @80cmdude or @HumanoidAsh wants to take a stab at it.

I'd fork it and do your changes there. Once happy start a merge request so I can check it over and get it merged into master. Ping me if you need any help to get started.

**Comment by HumanoidAsh** [comment]
Is there a repo for the disbott site?
=s

**Comment by 80cmdude** [comment]
disbott > web > index.html

**Comment by tomopagu** [comment]
^^ As @80cmdude said you can find the disbott site at https://github.com/tomopagu/disbott/blob/master/web/index.html when you clone/fork it'll be at `disbott/web/index.html`.

I'd recommend installing node and doing an `npm install` within the `disbott/` folder. Then you can just run `npm run start:web` to start a local webserver on port 5000 -> http://0.0.0.0:5000.

**Comment by 80cmdude** [comment]
Are you wanting me to leave this as 1 page or are you bothered if i put in multiple pages (without full page refresh)? The banner will stay Constant. I wan't to add a more obvious tutorial in a separate place.

**Comment by tomopagu** [comment]
Not bothered at all! I just went single page for quickness but having everything separated might be quite nice. Like the idea of a tutorial page.

**Comment by tomopagu** [comment]
Linked to PR #22

**Comment by tomopagu** [comment]
This was merged into master, so closing
